export default [
    {
        id: 1,
        name: 'КОМБО КУРА',
        isHit: false,
        isNew: true,
        description: 'Куриные крылья 420 г, наггетсы 170 г, сырные палочки 120 г, картофель фри 100 г, картофель дольки 100 г. Соусы барбекю, ранч и сырный',
        sauce_is_gift: false,
        image: 'https://pizza30cm.ru/wp-content/themes/yootheme/cache/img_22481-d45c33be.jpeg',
        price: 997,
        sale_price: 1297
    },
    {
        id: 2,
        name: 'Четыре мяса 30 см',
        isHit: true,
        isNew: false,
        description: 'томатный соус, колбаски охотничьи, свинина шейка, куриное мясо, ветчина. 490 гр. ',
        sauce_is_gift: true,
        image: 'https://pizza30cm.ru/wp-content/themes/yootheme/cache/pizza-11-f462114a.jpeg',
        price: 399,
        sale_price: 0
    },
    {
        id: 3,
        name: 'Карбонара 30 см',
        isHit: true,
        isNew: false,
        description: 'томатный соус, сыр моцарелла, грибы, бекон, желток куриный. 490 гр.',
        sauce_is_gift: true,
        image: 'https://pizza30cm.ru/wp-content/themes/yootheme/cache/pizza-06-e64872bc.jpeg',
        price: 399,
        sale_price: 0
    },
    {
        id: 4,
        name: 'ЧЕТЫРЕ КУРЫ',
        isHit: false,
        isNew: true,
        description: 'Четыре вида крыльев по 300 грамм каждого вида: Барбекю, в кисло-сладком соусе, в соусе Терияки, в остром чили-соусе.\n' +
            'Общий вес блюда 1200 г без коробки, с коробкой 1320 г',
        sauce_is_gift: false,
        image: 'https://pizza30cm.ru/wp-content/themes/yootheme/cache/4-kuri-c662abb8.png',
        price: 997,
        sale_price: 1297
    },
    {
        id: 5,
        name: 'Четыре сыра 30 см',
        isHit: true,
        isNew: false,
        description: 'томатный соус, сыр моцарелла, сыр фета, сыр чеддер, сыр креметте. 460 гр.',
        sauce_is_gift: true,
        image: 'https://pizza30cm.ru/wp-content/themes/yootheme/cache/pizza-10-5b26830d.jpeg',
        price: 399,
        sale_price: 0
    },
    {
        id: 6,
        name: 'Барбекю 30 см',
        isHit: true,
        isNew: false,
        description: 'томатный соус, сыр моцарелла, мясо куриное, перец сладкий, соус барбекю. 480 гр.',
        sauce_is_gift: true,
        image: 'https://pizza30cm.ru/wp-content/themes/yootheme/cache/pizza-12-dedea1c2.jpeg',
        price: 399,
        sale_price: 0
    },
    {
        id: 7,
        name: 'Пицца с морепродуктами 30 см',
        isHit: false,
        isNew: false,
        description: 'тесто, микс морепродуктов, соус сырный, томаты, сыр фета. 530 гр.',
        sauce_is_gift: true,
        image: 'https://pizza30cm.ru/wp-content/themes/yootheme/cache/pizza-seafood-f3f41c74.png',
        price: 399,
        sale_price: 0
    },
    {
        id: 8,
        name: 'Мясная с дымком 30 см',
        isHit: false,
        isNew: false,
        description: 'Соус гриль, фарш домашний, микс сыров, помидоры свежие, бекон. 555 гр.',
        sauce_is_gift: true,
        image: 'https://pizza30cm.ru/wp-content/themes/yootheme/cache/pizza-smokemeat-1-0e8eae2f.png',
        price: 399,
        sale_price: 0
    },
    {
        id: 9,
        name: 'Пицца Жюльен 30 см',
        isHit: false,
        isNew: false,
        description: 'Сырно-сливочный соус, куриное филе, грибы, соус жюльен. 520 гр.',
        sauce_is_gift: true,
        image: 'https://pizza30cm.ru/wp-content/themes/yootheme/cache/pizza-julien-63238dac.png',
        price: 399,
        sale_price: 0
    },
    {
        id: 10,
        name: 'ЧИЗБУРГЕР (Пицца-торт) 5 этажей',
        isHit: false,
        isNew: false,
        description: 'томатный соус, соус Бургер, фарш домашний, сыр плавленый, помидоры свежие, лук красный, огурцы маринованые, микс сыров, сыр чеддер, бекон, петрушка. 1 200 гр.',
        sauce_is_gift: false,
        image: 'https://pizza30cm.ru/wp-content/themes/yootheme/cache/7p4a3623-copy-d9f36326.png',
        price: 997,
        sale_price: 0
    },
    {
        id: 11,
        name: 'Мексиканская 30 см',
        isHit: false,
        isNew: false,
        description: 'томатный соус, сыр моцарелла, сладкий перец, свинина шейка, куриное мясо барбекю, перец свежий, перец халапеньо, хлопья чили. 540 гр.',
        sauce_is_gift: true,
        image: 'https://pizza30cm.ru/wp-content/themes/yootheme/cache/pizza-09-66060014.jpeg',
        price: 399,
        sale_price: 0
    },
    {
        id: 12,
        name: 'Шаверма 30 см',
        isHit: false,
        isNew: false,
        description: 'курица, маринованные огурцы, помидоры, сыр чеддер, сливочно-чесночный соус. 520 гр.',
        sauce_is_gift: true,
        image: 'https://pizza30cm.ru/wp-content/themes/yootheme/cache/pizza-07-490ce0fb.jpeg',
        price: 399,
        sale_price: 0
    },
    {
        id: 13,
        name: 'Пепперони 30 см',
        isHit: false,
        isNew: false,
        description: 'томатный соус, сыр моцарелла, пеперони. 405 гр. ',
        sauce_is_gift: true,
        image: 'https://pizza30cm.ru/wp-content/themes/yootheme/cache/pizza-04-63b05073.jpeg',
        price: 399,
        sale_price: 0
    },
    {
        id: 14,
        name: 'Ранч 30 см',
        isHit: false,
        isNew: false,
        description: 'Кура, бекон, соус ранч. 540 гр.',
        sauce_is_gift: true,
        image: 'https://pizza30cm.ru/wp-content/themes/yootheme/cache/ranch-1-67c0d97c.jpeg',
        price: 399,
        sale_price: 0
    },
    {
        id: 15,
        name: 'Ветчина и грибы 30 см',
        isHit: false,
        isNew: false,
        description: 'томатный соус, сыр моцарелла, ветчина, грибы. 480 гр.',
        sauce_is_gift: true,
        image: 'https://pizza30cm.ru/wp-content/themes/yootheme/cache/pizza-13-719a3385.jpeg',
        price: 399,
        sale_price: 0
    },
    {
        id: 16,
        name: 'Гавайская 30 см',
        isHit: false,
        isNew: false,
        description: 'томатный соус, сыр моцарелла, ветчина, ананас, перец свежий. 520 гр.',
        sauce_is_gift: true,
        image: 'https://pizza30cm.ru/wp-content/themes/yootheme/cache/pizza-08-c9429253.jpeg',
        price: 399,
        sale_price: 0
    },
    {
        id: 17,
        name: 'Маргарита 30 см',
        isHit: false,
        isNew: false,
        description: 'томатный соус, двойная моцарелла, помидоры свежие. 530 гр. ',
        sauce_is_gift: true,
        image: 'https://pizza30cm.ru/wp-content/themes/yootheme/cache/pizza-03-998da324.jpeg',
        price: 399,
        sale_price: 0
    },
    {
        id: 18,
        name: 'Вегетарианская 30 см',
        isHit: false,
        isNew: false,
        description: 'томатный соус, сыр моцарелла, перец сладкий, грибы, помидоры свежие, перец халапеньо. 520 гр.',
        sauce_is_gift: true,
        image: 'https://pizza30cm.ru/wp-content/themes/yootheme/cache/pizza-14-8ba7c0d2.jpeg',
        price: 399,
        sale_price: 0
    },
    {
        id: 19,
        name: 'Осетинский пирог с ветчиной и сыром',
        isHit: false,
        isNew: false,
        description: 'Микс сыров, ветчина, картошка, жареный лук. 520 гр',
        sauce_is_gift: true,
        image: 'https://pizza30cm.ru/wp-content/themes/yootheme/cache/01-2-75cdc21d.jpeg',
        price: 399,
        sale_price: 0
    },
    {
        id: 20,
        name: 'Осетинский пирог с курой и сыром',
        isHit: false,
        isNew: false,
        description: 'микс сыров, куриное филе, грибы шампиньоны, жареный лук. 520 гр',
        sauce_is_gift: true,
        image: 'https://pizza30cm.ru/wp-content/themes/yootheme/cache/01-2-75cdc21d.jpeg',
        price: 399,
        sale_price: 0
    },
    {
        id: 21,
        name: 'Осетинский пирог с картошкой и сыром',
        isHit: false,
        isNew: false,
        description: 'микс сыров, картофель, жареный лук. 520 гр',
        sauce_is_gift: true,
        image: 'https://pizza30cm.ru/wp-content/themes/yootheme/cache/01-2-75cdc21d.jpeg',
        price: 399,
        sale_price: 0
    },
    {
        id: 22,
        name: 'Пирог Абрикосовый',
        isHit: false,
        isNew: false,
        description: 'тесто дрожжевое, абрикос фружеле, курага, сахарная пудра. 700 гр.',
        sauce_is_gift: false,
        image: 'https://pizza30cm.ru/wp-content/themes/yootheme/cache/cake-02-2d258201.png',
        price: 399,
        sale_price: 0
    },
    {
        id: 23,
        name: 'Пирог Черничный',
        isHit: false,
        isNew: false,
        description: 'тесто дрожжевое, черника фружеле, сахарная пудра. 700 гр.',
        sauce_is_gift: false,
        image: 'https://pizza30cm.ru/wp-content/themes/yootheme/cache/cake-01-07993289.png',
        price: 399,
        sale_price: 0
    },
    {
        id: 24,
        name: 'Компот из сухофруктов 1 литр',
        isHit: false,
        isNew: false,
        description: 'сухофрукты (яблоко, курага, чернослив, изюм), вода, сахар, лимонная кислота, куркума, имбирь, лавр благородный.',
        sauce_is_gift: false,
        image: 'https://pizza30cm.ru/wp-content/themes/yootheme/cache/eei5cah03ri-746ade5f.jpeg',
        price: 150,
        sale_price: 0
    },
    {
        id: 25,
        name: 'Морс ягодный 1 литр',
        isHit: false,
        isNew: false,
        description: 'ягода красная, вода, сахар, лимонный сок, бадьян, суданская роза.',
        sauce_is_gift: false,
        image: 'https://pizza30cm.ru/wp-content/themes/yootheme/cache/ztcyad5ytuk-1f7b3bea.jpeg',
        price: 150,
        sale_price: 0
    },
]